### ISSUE TITLE
How to enable DND

### ISSUE THREAD

**Issue by danielgomezrico** [arodik/mindful-timer#3]
Hi 

Im using OSX 11.2 Big Sour
I run `mindful-timer start 25` and do not disturb does not enable, it stays like this:

![image](https://user-images.githubusercontent.com/76348/107694717-b3e87580-6c7d-11eb-84b5-ee7600ad94d0.png)

**Comment by arodik** [comment]
There is a problem with switching do not disturb mode on macOS Big Sur :( 
I'm working on it and I'm going to release the fix soon.

**Comment by arodik** [comment]
I use `sindresorhus/do-not-disturb` package and it doesn't work with Big Sur. Guys in [this issue](https://github.com/sindresorhus/do-not-disturb/issues/9) proposed a solution, will try it soon.

**Comment by arodik** [comment]
Done) Please, try [0.4.2](https://github.com/arodik/mindful-timer/releases/tag/v0.4.2)

**Comment by danielgomezrico** [comment]
@arodik it works! thanks
